version: "2"
services:
  redis-master: 
    image: redis:3.2.5-alpine
    volumes:
      - "./.data:/data"

  redis-slave:
    image: redis:3.2.5-alpine
    command: redis-server --slaveof redis-master 6379
    links:
      - redis-master
    volumes:
      - "./.data:/data"  
        
  redis-sentinel:
    build:
      context: ./redis-sentinel
    links:
      - redis-master      